### PR TITLE
Gas giants fix with EVO configs and textures

### PR DESCRIPTION
**Pull request by thething252**

### CODE REVIEW

**Review by thething252 — COMMENTED** [review]
yes

**Comment by thething252** [comment]
The textures from EVO are from the Celestia Motherlode

**Comment by thething252** [comment]
This PR fixes all the gas giant bugs

**Comment by thething252** [comment]
It fixes issue #29 and I could try lower cloud shadow factor later

**Review by siimav — CHANGES_REQUESTED** [review]
Among the listed changes, this also appears to overwrite each and every cfg file in the mod. Probably mismatched line endings or tabs vs spaces.

**Pull request closed without merging**
