### PR TITLE
lower cloud shadow factor to 0

### PR DESCRIPTION
**Pull request by thething252**

### CODE REVIEW

**Comment by siimav** [comment]
You sure it has to be 0? The cloud shadows add a lot of depth when viewed from LEO.

**Comment by thething252** [comment]
I recknon we can change it to 1 then

**Comment by Capkirk123** [comment]
Yes, the current cloud shadow factor is a little overkill, but I don't think we should remove shadows completely.

**Comment by Capkirk123** [comment]
Will this resolve https://github.com/KSP-RO/RSSVE/issues/25 ?

**Comment by thething252** [comment]
It would fix #25 partly, I’m not sure about the option that disabled them not working. I will remove my pr which suggests disabling them by default

**Pull request closed without merging**
